sudo: required

dist: xenial

language: java

# services:
#   - docker 

env:
  - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64

# Run before every job
before_install:
  - sudo apt-get update
  - sudo apt-get install -y openjdk-8-jdk
  - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//')
  - java -version
  - uname -a
  - chmod +x pom.xml


# This is only run before integrationTests job
# To ensure docker containers are fully up and running we sleep 20s
# before_script:
#   - cd src/main/docker/
#   - source env.bash
#   - docker-compose up -d
#   - sleep 60
#   - cd ../../../


# Generate site documentation using mvn site plugin
# before_deploy:
#   - rm -rf docs
#   - mvn site -B


# Using default stage 'test' for all our test jobs, and only running deploy stage
# (after merge) to master branch
stages:
  - test
#   - name: deploy
#     if: branch = master


# List of jobs to run, tied to specific stages
jobs:
  include:
    - stage: test
      name: AllTests
      before_script: skip
      script:
        - mvn test -B
